server:
  port: 8012

spring:
  application:
    name: ConfigServer

  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hwajin15/MyAppConfiguration.git
          username: hwajin15
          password: ckdals0218!
          clone-on-start: true
        native:
          search-locations: file:///${user.home}/Work/dev


  rabbitmq:
    host: localhost
    port: 25672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
