server:
  port: 8012

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hwajin15/MyAppConfiguration.git
          username: hwajin15
          password: ckdals0218!
          clone-on-start: true
